/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligamx;

/**
 *
 * @author Josue
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AltaJugadores = new javax.swing.JButton();
        ListaJugadores = new javax.swing.JButton();
        AltaEquipo = new javax.swing.JButton();
        ListaEquipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(676, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ligamx/MX_logo.png"))); // NOI18N

        AltaJugadores.setBackground(new java.awt.Color(204, 204, 204));
        AltaJugadores.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        AltaJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ligamx/Jugador.png"))); // NOI18N
        AltaJugadores.setText("ALTA DE JUGADORES");
        AltaJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaJugadoresActionPerformed(evt);
            }
        });

        ListaJugadores.setBackground(new java.awt.Color(204, 204, 204));
        ListaJugadores.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ListaJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ligamx/Jugadores.png"))); // NOI18N
        ListaJugadores.setText("LISTA DE JUGADORES");
        ListaJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaJugadoresActionPerformed(evt);
            }
        });

        AltaEquipo.setBackground(new java.awt.Color(204, 204, 204));
        AltaEquipo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        AltaEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ligamx/Equipo.png"))); // NOI18N
        AltaEquipo.setText("ALTA DE EQUIPO");
        AltaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaEquipoActionPerformed(evt);
            }
        });

        ListaEquipos.setBackground(new java.awt.Color(204, 204, 204));
        ListaEquipos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ListaEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ligamx/Equipos.png"))); // NOI18N
        ListaEquipos.setText("LISTA DE EQUIPOS");
        ListaEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AltaJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AltaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AltaJugadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ListaJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AltaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaJugadoresActionPerformed
        AltaJugadores ven = new AltaJugadores(this,true);
        ven.setVisible(true);
    }//GEN-LAST:event_AltaJugadoresActionPerformed

    private void ListaJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaJugadoresActionPerformed
        ListaJugadores ven = new ListaJugadores(this,true);
        ven.setVisible(true);
    }//GEN-LAST:event_ListaJugadoresActionPerformed

    private void AltaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaEquipoActionPerformed
        AltaEquipo ven = new AltaEquipo(this,true);
        ven.setVisible(true);
    }//GEN-LAST:event_AltaEquipoActionPerformed

    private void ListaEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaEquiposActionPerformed
        ListaEquipos ven = new ListaEquipos(this,true);
        ven.setVisible(true);
    }//GEN-LAST:event_ListaEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltaEquipo;
    private javax.swing.JButton AltaJugadores;
    private javax.swing.JButton ListaEquipos;
    private javax.swing.JButton ListaJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
